### ISSUE TITLE
Command: wp plugin is-active

### ISSUE THREAD

**Issue by bjorngustafsson** [wp-cli/ideas#102]
I want basically the same functionality as in the `wp plugin is-installed` but instead it checks if a plugin is active, for example `wp plugin is-active nameofplugin`. I could do this and send in a pull request if you want.

**Comment by schlessera** [comment]
@bjorngustafsson Sounds like a useful addition. Please go ahead with the pull request, and model it after `wp plugin is-installed`.

**Comment by marksabbath** [comment]
Should be resolved by https://github.com/wp-cli/extension-command/pull/102
