### ISSUE TITLE
Suppress global parameters

### ISSUE THREAD

**Issue by dotancohen** [wp-cli/ideas#104]
As a regular user of WP-CLI, I've got the Global Parameters memorized. I suggest adding a config option to the wp-cli script which would suppress the display of the Global Parameters on `wp help foo` invocations.

```
suppress_global_params: true
```

**Comment by schlessera** [comment]
I too think that we're being wasteful of screen estate for people that know their way around the tool. Adding such a config option for power users would certainly help.

**Comment by danielbachhuber** [comment]
If we added this, we'd want to do so with an environment variable.

**Comment by flythenimbus** [comment]
@dotancohen Can you please clarify what you mean by "global parameters"? Can you post an example?

**Comment by chesio** [comment]
@dugajean I believe he meant these parameters: https://make.wordpress.org/cli/handbook/references/config/#global-parameters
