### ISSUE TITLE
remove all tables from db without dropping the db (wp db reset --tables)

### ISSUE THREAD

**Issue by cfoellmann** [wp-cli/ideas#106]
I just recently realized that not using wp-cli is stupid 😈 and scripted some stuff to reset dev sites to a snapshot.
It took me an hour to realize that when I do a `wp db reset` the database is dropped which is a very un-intuitive result to me.

I would propose adding an option (maybe not the best name for the option):
```
[--tables]
Drops all tables in the database leaving the database intact.
```

Currently I use this workaround: https://stackoverflow.com/questions/12403662/how-to-remove-all-mysql-tables-from-the-command-line-without-drop-database-permi/18625545#18625545

```mysql
-- Drop all tables from current database

SET FOREIGN_KEY_CHECKS = 0;
SET GROUP_CONCAT_MAX_LEN=32768;
SET @tables = NULL;
SELECT GROUP_CONCAT('`', table_name, '`') INTO @tables
  FROM information_schema.tables
  WHERE table_schema = (SELECT DATABASE());
SELECT IFNULL(@tables,'dummy') INTO @tables;

SET @tables = CONCAT('DROP TABLE IF EXISTS ', @tables);
PREPARE stmt FROM @tables;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET FOREIGN_KEY_CHECKS = 1;
```

**Comment by schlessera** [comment]
Thanks for the feedback, @cfoellmann !

This functionality has already been implemented via https://github.com/wp-cli/db-command/issues/92 and will be part of the next release (v2.0.0).

**Comment by cfoellmann** [comment]
thanks for the info and the fast clarification.
I only searched the ideas and the wp-cli repo
