### ISSUE TITLE
Desktop notification for Success, Warning and Error

### ISSUE THREAD

**Issue by abhijitrakas** [wp-cli/ideas#107]
I think system notification for `success`, `warning` and `error` would be helpful during development. 

Please check the following screenshot for more details. 

![wpcli-error-notification](https://user-images.githubusercontent.com/26354653/44297928-4c911b00-a2f7-11e8-9334-c61da665b1ba.png)

![wpcli-success-notification](https://user-images.githubusercontent.com/26354653/44297930-53b82900-a2f7-11e8-8922-1fbea445c8a6.png)

I am using  [JoliNotif library](https://github.com/jolicode/JoliNotif) to set a desktop notification. 

Will this be helpful? Let me know your thogughts.

Thanks

**Comment by swissspidy** [comment]
I guess this would need to be opt-in, as not everybody would want desktop notifications, especially when you already have the UI. Perhaps it could be an installable package that just extends the default logger?

Besides that, I just tried to install JoliNotif globally using Composer on macOS and couldn't get it to work with CLI, so I'm not sure how well it really works...

**Comment by abhijitrakas** [comment]
@swissspidy Thanks, for the reply and sorry for my late reply.
> Perhaps it could be an installable package that just extends the default logger?  

Yes, it can be optional, but as you tested on macOS and `JoliNotif` library not working for you that means first I need to test it on macOS. If it work there then only will try for package. Thanks again.

**Comment by danielbachhuber** [comment]
> Perhaps it could be an installable package that just extends the default logger?

👍 to this idea.

**Comment by abhijitrakas** [comment]
@swissspidy @danielbachhuber 
How do I extend default logger to accomplish this? Do I need to redefine method using `runkit_method_add ` this PHP function? 

Thanks.

**Comment by danielbachhuber** [comment]
@abhijitrakas What have you tried?

**Comment by abhijitrakas** [comment]
Not tried anything yet because I am stuck in `how to extend default logger?`. (so added comment :point_up: )

**Comment by danielbachhuber** [comment]
@abhijitrakas You can set a new logger instance with `WP_CLI::set_logger()`: https://github.com/wp-cli/wp-cli/blob/master/php/class-wp-cli.php#L26-L33

Something like this:

```
$logger = new My_Logger_Class;
WP_CLI::set_logger( $logger );
```

**Comment by abhijitrakas** [comment]
@danielbachhuber Thanks for your help. I have created package. Please have a [look](https://github.com/abhijitrakas/wp-cli-notification) and let me know your suggestions.

**Comment by danielbachhuber** [comment]
👍 Package looks great! It'd be great to have some screenshots in there: https://github.com/abhijitrakas/wp-cli-notification/issues/1

**Comment by abhijitrakas** [comment]
@danielbachhuber Thanks for issue, Screenshot added.  

Do I need to upload this package on [Packagist](https://packagist.org)? to make it available in list of `wp package browse`.

**Comment by danielbachhuber** [comment]
> Do I need to upload this package on [Packagist](https://packagist.org)? to make it available in list of `wp package browse`.

If you'd like to upload it to Packagist, you can.

However, `wp package browse` is powered by the WP-CLI package index (a separate Packagist instance), which is deprecated and has no replacement: https://github.com/wp-cli/ideas/issues/51

**Comment by abhijitrakas** [comment]
@danielbachhuber @swissspidy 🙏 Thanks for your support throughout the release. You guys are awesome. I am closing this issue as no longer needed.
