### ISSUE TITLE
Add option to eval-file for ignoring first line / shebang

### ISSUE THREAD

**Issue by stefanfisk** [wp-cli/ideas#108]
If we add an option to ignore the first line of the input file WP CLI could be used for writing WP-centric scripts that one can call from the command line. The use case I primarily see is helping with doing one time tasks, personally I for example wanted to run a quite complex ImageMagick command on all featured images for posts of a specific type.

Currently `wp eval-file` can actually be used like this, but since the shebang is parsed as PHP it is echoed, which interferes when you want to use the script output for other things.

So, this is what I want to be able to do:
```PHP
#!/bin/env wp eval-file
<?php
echo get_bloginfo('name');
```

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @stefanfisk.

I don't think this needs to be an option, per se. We can improve the behavior of `wp eval-file` to strip out the shebang from the first line of the file if it detects it. Want to put together a pull request for this?

**Comment by stefanfisk** [comment]
Great! I'm not sure when exactly I'd get around to it as it would be my first time building WP CLI, but expect a pull request eventually!

So essentially `_eval()` in https://github.com/wp-cli/eval-command/blob/master/src/EvalFile_Command.php would check for the shebang, and if it's there strip the first line and feed the result to `eval()`?

**Comment by danielbachhuber** [comment]
> So essentially `_eval()` in https://github.com/wp-cli/eval-command/blob/master/src/EvalFile_Command.php would check for the shebang, and if it's there strip the first line and feed the result to `eval()`?

Yep, I think so. I had forgotten the implementation was `include $file;` instead of `eval( file_get_contents( $file ) );`. We may be able to switch to the latter, as long as they're functionally equivalent. Or, we could only use the latter if WP-CLI detects `#!/` at the beginning of the file.

**Comment by phlbnks** [comment]
(Working on this at WCLDN)

**Comment by danielbachhuber** [comment]
Landed in https://github.com/wp-cli/eval-command/pull/35
