### ISSUE TITLE
Add force flag to import database

### ISSUE THREAD

**Issue by abhijitrakas** [wp-cli/ideas#112]
Can we add `--force` flag in `wp db import` command to continue importing even after an error found?

Sometimes `.sql` the file might have some bad data which stops the process. It will be good if the user has an option of this flag to import data forcefully.

**Comment by schlessera** [comment]
I think this use case makes sense and we should support it.

I'm not yet sure about the specific way to support it, though. I can think of two different approaches:

1. Using a singular flag, like proposed above.
2. Making the `db import` work similarly to the `db export` command in that you can add any arguments supported by the `mysql` client, and they will be forwarded when executing the query. This way, you can use the `--force` argument provided by `mysql`, but also any other qualifying flags you might need.

**Comment by renatonascalves** [comment]
It seems the second option will add more flexibility for other flags one might want to use.

**Comment by abhijitrakas** [comment]
When I was writing this idea, was thinking about the second option. The second option makes more sense. I think we should go with the second option.

**Comment by schlessera** [comment]
Great, let's do this. I'll accept PRs for the second option above.

**Comment by abhijitrakas** [comment]
Awesome. Will start work on this from tomorrow.

**Comment by schlessera** [comment]
Fixed via https://github.com/wp-cli/db-command/pull/123
