### ISSUE TITLE
WP-CLI project health metrics

### ISSUE THREAD

**Issue by schlessera** [wp-cli/ideas#113]
WP-CLI should collect and monitor metrics that relate to maintenance activity and project health.

I think it makes sense to have two sets of metrics that we should track and set goals against: **maintenance metrics** & **project health metrics**.

---

The **maintenance metrics** are the ones that keep the maintainer(s) accountable and ensure they can provide reasonable expectations towards contributors. They measure things the maintainers can directly act upon.

* **Average ticket response time** (measured on issues & pull requests) - people should expect a timely answer, unless all maintainers are OOO. Goal = 3 days or less.
* **Average ticket lifetime** (measured on issues & pull requests) - how quickly can we solve tickets? Ideally, categorized based on GH labels. Goal = 5 days or less for high-priority categories ("bug", ?).
* **Average time without activity** (measured on issues & pull requests) - how well are keeping the wheels in motion?

What seems to be missing here is the number of open tickets. While we can certainly collect this data as well, I don't think it should be a metric feeding a goal. Just reducing the number of open tickets for the sake of fulfilling such a goal would be detrimental for attracting potential new contributors, and optimizing for the other metrics will naturally keep the number in reasonable ranges anyway.

---

The **project health metrics** are more indirect and cannot directly be acted upon. They show the long-term effects and trends that the maintenance work produces and can guide roadmap priorities.

* **Average # of active contributors** (rolling average measured as having been active on GitHub or Slack in the last 60 (?) days) - shows how involved people are and shows things like seasonality, allowing for better planning windows. Goal = upward trend.
* **Average # of tickets labeled as bug** (rolling average measured as on GitHub label "bug" in the last 60 (?) days) - is QA good enough? Goal = downward trend.

---

We will build scripts to capture these metrics and then run them daily and collect statistical data this way. This not only serves the individual goals that each metric pursues, but also allows for more meaningful regular status updates to WP leadership and users.

The above is a first iteration and still WIP. I'm opening an issue here to invite discussion with the borader WP-CLI community.

**Comment by schlessera** [comment]
I looked at a few existing solutions to do this. Some seem to be complete enough to collect what we need in a reliable manner, however, they are always implemented on completely different technological stacks (or not even open source). I would prefer to have a PHP solution to keep work on it within the technological expertise of our contributors.

For historical data we can query rolling averages on, relying on direct access to the GitHub API is not an option due to the sheer volume of data and the API rate limits (5000 requests per hour when using an access token). To solve this, we would need to build (a simplified) data warehouse where we store and transform the data in background jobs, and then execute the queries on this data warehouse. The main benefit of such a data warehouse approach is that we can collect the data incrementally, instead of always having to retrieve the entire data set we need for a given query. This should enable us to make this work within the strict rate limits of the API.

To maximize the amount of data we can gather and keep in sync, we should store all items in the data warehouse with an expected life span and only refetch it if it has gone past this life span (i.e. become stale). This allows us for example to put a much higher life span on closed issues (1 month?) then on open ones (1 day).

Note: While the above might seem complicated, it is unfortunately needed, because we need all of our metrics to be based on the organization's data, not on the data of a single repository. GitHub does not provide useful querying capabilities at the organizational level.

Generalized process:

1. Collect data incrementally from GitHub while being smart about pagination, rate limits, and expiration
2. Create daily denormalized snapshots of the key data we need for our metrics.
3. Build reports or a dashboard that query the denormalized snapshots and trigger notifications under certain circumstances.

Some related links:
- https://opensource.guide/metrics/
- https://developer.github.com/v3/
- https://blog.novoda.com/github-data-mining-101/
- https://github.com/novoda/github-reports
- https://chaoss.github.io/grimoirelab/
- https://github.com/chaoss/grimoirelab-perceval
- http://decisionlab.io/blog/2017/06/30/data-story-github-stats-organization
- https://github.com/KnpLabs/php-github-api
- https://github.com/yaronn/blessed-contrib (for the CLI fun)

**Comment by danielbachhuber** [comment]
We have a first pass at this as of https://github.com/wp-cli/.github/issues/24

It lives here: https://wp-cli.org/dashboard/

Enhancements can be filed here: https://github.com/wp-cli/dashboard/issues

🚢
