### ISSUE TITLE
Introduce maintenance mode

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/ideas#114]
Laravel's artisan command has maintenance mode command: up and down.
I am new to CI regarding WordPress but it is clear that during deployment a site should be shut down.

Currently this hack does it.

```shell
wp eval 'WP_Filesystem();require_once ABSPATH."wp-admin/includes/class-wp-upgrader.php";(new WP_Upgrader())->maintenance_mode(true);'
```

It would be nice to get comments and get it implemented also.

`wp core down`

**Comment by schlessera** [comment]
Yes, I can see this being useful.

I think having this under `core` would be misleading, I'd prefer a `wp maintenance` command with a few actions instead:

- `wp maintenance on [--force]`
- `wp maintenance off [--force]`
- `wp maintenance status`

A force switch is probably needed for the cases where something is borked.

On a more general note: If you are doing CI, you would normally want your deployments to be atomic, so maintenance mode is not needed in that case.

**Comment by swissspidy** [comment]
Shouldn't be too hard to implement this I think. The proposed command makes sense.

I think it can also be useful when you want to quickly disable maintenance mode after some failed update where WordPress wasn't able to remove the file. This way you don't have to manually remove the file.

**Comment by thrijith** [comment]
@swissspidy @schlessera 

[Here](https://github.com/thrijith/wp-cli/pull/2/files) is the current status of this idea. 

Only blocker I am facing is that, it  outputs `<p>maintenance_start</p>` when invoked, couldn't find a way to capture it. `ob_*` functions didn't work.

PS: Not sure about the syntax though, Please check [this](https://github.com/wp-cli/wp-cli-dev#wp-maintenance).

**Comment by szepeviktor** [comment]
Thank you.
There is a similar issue with the upgrader skin: it is HTML only.
