### ISSUE TITLE
Proposal - Add WP CLI to Debian

### ISSUE THREAD

**Issue by jonathanbossenger** [wp-cli/ideas#121]
Yesterday I discovered that WordPress is available as a Debian package

https://wiki.debian.org/WordPress

As a Linux user, I would assume that WP CLI would make much more sense as a Debian package, especially for web hosts. I'm also led to understand that this requires an individual to commit to maintaining the package in the Debian repositories.

I am prepared to be that person, to be honest I have no idea what this entails, but I'm willing to find out.

Before I do so however, does the WP CLI community think this is a good idea? If this does not fit within the goals of the project, there's no reason to research how to do it.

**Comment by chesio** [comment]
Hi @jonathanbossenger,

There are Debian packages, they are just not available via Debian repositories, see: https://github.com/wp-cli/wp-cli/issues/4598

**Comment by jonathanbossenger** [comment]
Thanks @chesio I'll continue the conversation there.
