### ISSUE TITLE
Create CODEOWNERS file for each repository

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/ideas#122]
If we create a CODEOWNERS file for each repository, we can automatically tag `@wp-cli/committers` for review on each pull request.

Personally, I think this would be helpful to keep better tabs of what's happening on a daily basis.

@wp-cli/committers Any opposition?

**Comment by swissspidy** [comment]
Let's try it out 👍

**Comment by schlessera** [comment]
Yes, let's see how this works out.

**Comment by danielbachhuber** [comment]
This is now done :)

**Comment by schlessera** [comment]
The one in `entity-command` is missing, as the commit was a `Delete` instead of a `Create`...

**Comment by danielbachhuber** [comment]
> as the commit was a `Delete` instead of a `Create`...

I accidentally added `CODEOWNERS` in the root. `CODEOWNERS` already exists in the `.github` directory: https://github.com/wp-cli/entity-command/tree/master/.github

**Comment by schlessera** [comment]
Ah, okay, that makes sense then.
