### ISSUE TITLE
Custom global parameters

### ISSUE THREAD

**Issue by david-binda** [wp-cli/ideas#126]
WP CLI Hooks triggering at various points of the WP CLI execution before WordPress is loaded theoretically allow package developers to not only introduce new commands, but also modify some bits of the WordPress load and behaviour (similarly to the `skip-themes`, `skip-plugins`, and/or `skip-packages` flags).

But there does not seem to be a way to properly register custom global parameters in WP CLI internal API, so my attempts to add any custom flag to all registered commands ends up with `Parameter errors`.

I believe that it would be cool to allow package developers to register a custom global parameters in order to provide some modified behaviour for WP CLI / WordPress.

It also feels like a possible internal api implementation, `WP_CLI::register_config_key`, was being considered in terms of https://github.com/wp-cli/wp-cli/issues/520

Based on the approved status of https://github.com/wp-cli/ideas/issues/104 it looks like global parameters are currently being regarded as something what does not get changed often, so the possible drawback would be the unpredictability of all existing global parameters in a specific installation, which could get fixed by introducing a new section of package registered global parameters, which would not be excluded in case the `suppress_global_params` is set.

**Comment by danielbachhuber** [comment]
> I believe that it would be cool to allow package developers to register a custom global parameters in order to provide some modified behaviour for WP CLI / WordPress.

@david-binda Do you recall your specific use case? I'm coming back around to this with https://github.com/wp-cli/wp-cli/issues/5649

**Comment by danielbachhuber** [comment]
This is now possible with https://github.com/wp-cli/wp-cli/pull/5664
