### ISSUE TITLE
Read-only mode

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/ideas#127]
Could we introduce a read-only mode for all operations?

I'd like to be on the safe side on production servers.

**Comment by schlessera** [comment]
I'm not sure this is entirely feasible. Some operations are just handed over to WordPress, so we can only "do the operation" or "NOT do the operation".

I think we should investigate where adding additional `--dry-run` flags makes sense, but I doubt we add it everywhere.

**Comment by szepeviktor** [comment]
I see, some commands maybe dry-run compatible.
