### ISSUE TITLE
Ensure WP Can Send Email Correctly

### ISSUE THREAD

**Issue by jakejackson1** [wp-cli/ideas#13]
I needed the ability to test if WP was correctly sending emails without any issues. I use an SMTP plugin and wanted to test the credentials were accurate. Doing it with a simple CLI command would be awesome.

**Comment by danielbachhuber** [comment]
Heh, maybe `wp mail`.

Did you know you can use `wp shell` or `wp eval` to call `wp_mail()`?

```
wp eval "wp_mail( 'test@example.org', 'My subject', 'My body' );"
```
