### ISSUE TITLE
Check cron job in past

### ISSUE THREAD

**Issue by Feriman22** [wp-cli/ideas#136]
Hi,

How can I check the cron jobs run is the past? I mean for example when was the last run of one cron job?

Is it possible?

Thanks!

**Comment by danielbachhuber** [comment]
Thanks for the question, @Feriman22

Unfortunately, past cron jobs are deleted, so there's no way to access their history.

**Comment by Feriman22** [comment]
Thanks, it's not relevant for me after 4 years :)
