### ISSUE TITLE
Custom wp-config.php file parameter for wp config set command

### ISSUE THREAD

**Issue by Peneheals** [wp-cli/ideas#138]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

I'm using custom wp-config.php files outside of the webroot on some hosts which are included in the normal wp-config.php files. It would be great to see a new `wp config set` option where I can set the full path of the included wp-config-custom.php or a related path from the wp-config.php and let the `wp config set` command set the desired variable there.

**Describe the solution you'd like**

Add a new parameter, for example `--config-file=<path>` and let the "magic" happen' in it, not just in the regular wp-config.php file.

**Comment by schlessera** [comment]
Yes, that makes sense to me. You might need to choose a different anchor then, but this is already supported by the current command.

**Comment by pmbaldha** [comment]
@schlessera @Peneheals I have opened two PRs:

1. https://github.com/wp-cli/config-command/pull/104
2. https://github.com/wp-cli/wp-cli/pull/5366
