### ISSUE TITLE
Idea for new members/developers

### ISSUE THREAD

**Issue by Sleo007** [wp-cli/ideas#143]
I was looking on Worpress.org for the ability to save/bookmark specific documents so that I could build a custom-tailored guide to my skill level for future reference (since the codex is massive). To my surprise, no such bookmarking or list function seems to be present. Would it be possible to implement such a feature? The most similar feature I can think of would be a YouTube playlist.

**Comment by chesio** [comment]
Hi @Sleo007,

Your request doesn't seem to be related to WP-CLI. Please, consider creating a new ticket in [WordPress.org Trac](https://meta.trac.wordpress.org/) - this is definitely a better place for ideas related to WordPress.org website.
