### ISSUE TITLE
Generate consumer key and consumer secret with WP CLI

### ISSUE THREAD

**Issue by yilmazchef** [wp-cli/ideas#144]
Dear WP CLI team,

I have been developing a cross-platform application that collects products information from multiple websites, and provides a match result for the end users.

I use WP CLI commands to create, edit, and generate fully funtional wordpress based woocommerce store. However, the only step I stucked is when I try to generate authentication keys (consumer_key and consumer_secret) via command line or via a rest call. I could not find a proper solution for that.

Could you please guide me on this.?

Sincere regards, and thank you very much for providing us such an amazing platform.

yilmazchef.

**Comment by danielbachhuber** [comment]
Sorry for the delay, @yilmazchef !

If you haven't already sorted this out, I'd recommend reaching out to the WooCommerce developer community. That's a more appropriate spot for functionality like this.
