### ISSUE TITLE
Plugin list to composer file

### ISSUE THREAD

**Issue by Horttcore** [wp-cli/ideas#15]
I personally using a composer setup for my development.
But sometimes clients/co-workers using the `install plugin` page instead if the cli tool ( which isn't a shocker). It would be awesome if there would be a command to update the composer file by wp-cli.

ie:
`wp composer plugins --all/--active`
`wp composer themes --all/--active`

It checks which plugins and themes are active and updates the composer file with these and deletes old entries.

**Comment by danielbachhuber** [comment]
There's an existing `wp composer` package that might be worth checking out: https://github.com/rxnlabs/wp-composer

**Comment by Horttcore** [comment]
Thank you! Didn't know that package.
