### ISSUE TITLE
Manage auto-updates (plugins/themes/core)

### ISSUE THREAD

**Issue by erickhavel** [wp-cli/ideas#150]
It would be very convenient to be able to manage (enable or disable) the new auto-updates through WP CLI.

Logical syntax I feel would be:

```wp core auto-updates enable|disable```

```wp plugin auto-updates enable|disable <plugin|--all>```

```wp theme auto-updates enable|disable <theme|--all>```

Thoughts?

**Comment by ponasromas** [comment]
Brilliant idea. Now we will wait few years it to mature.

**Comment by PontusTideman** [comment]
Check nightly: [https://twitter.com/wpcli/status/1310918586249207815](https://twitter.com/wpcli/status/1310918586249207815)
