### ISSUE TITLE
 Modify sections of an existing site by configuration / template

### ISSUE THREAD

**Issue by martinmurciego** [wp-cli/ideas#154]
## Feature Request

Congratulations on this tool!
I suggest I do not know how it would be done that given a website made with a template and data such as title, icon, address, links, to be able to generate a configuration that allows altering the data as a template of your site. So that you can clone the site and alter it programmatically.

Being able to modify links, email, telephone numbers, images, titles, etc. in an easy way by wp cli.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @martinmurciego !

This sounds like it would be a better fit for a third-party package. Feel free to share it here if you create one.
