### ISSUE TITLE
Add --domain option to "create site"

### ISSUE THREAD

**Issue by Sheraf1** [wp-cli/ideas#156]
Hi,

I cant find a way to set a different domain for a site created using WP CLI, the only option available is slug
and even after creating a subdirectory site i cant find how to update the site address to a different domain (available in the wordpress interface)
I can change the siteurl and homepage but i still need to change the "Site Address (URL)" in the multisite setup

Thanks

**Comment by danielbachhuber** [comment]
@Sheraf1 Sorry for the late reply here!

On the off chance you still remember this issue, could you share the command you ran, the output you saw, and your expected output?
