### ISSUE TITLE
New command proposal :  wp core authentication

### ISSUE THREAD

**Issue by mrmakadia94** [wp-cli/ideas#161]
### Feature Request
--------

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributions/contributing/).

Securing The WordPress with HTTP Authentication,

#### Describe your use case and the problem you are facing

A new cli command to enable the http authentication for website.

#### Describe the solution you'd like

I imagine something like:
`$ wp core  authentication`

There are two options like `[--username=<username>]` and `[--password=<password>]`

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @mrmakadia94 !

> A new cli command to enable the http authentication for website.

I'm not sure I follow. Could you describe what you mean by this with greater detail?
