### ISSUE TITLE
Add a command to retrieve values from WP CLI config file(s)

### ISSUE THREAD

**Issue by baizmandesign** [wp-cli/ideas#177]
## Feature Request

I'd like to have a command that enables me to retrieve values from a user's `config.yml` file (or the combination of all configuration files parsed by WP CLI).

This is already the case for aliases. They are defined in a YML file, and `wp cli alias <subcommand>` lets us retrieve (and update) alias settings.

Here's an example snippet from my `~/.wp-cli/config.yml`:

```
config create:
     dbuser: root
     dbpass: root
     dbhost: 127.0.0.1

core install:
     admin_user: saul
     admin_password: saul
     admin_email: saul@baizmandesign.com
```

I'd like to run a command that, for example, returns the value of **dbpass** under **config create**. (A further step, which I'm not advocating for right now, might entail setting that value.)

Yes, I can use external shell commands such as grep and awk, but they don't natively parse YML files. I'd love a solution provided by WP CLI itself.

The syntax of the command I'm proposing is a little unclear to me. Here's one possibility:

```
$ wp cli config get "config create > dbpass"
```

I'm not sure using ">" is the right way to express the hierarchical relationship between the parent / child elements.

**Comment by swissspidy** [comment]
Just re-sharing https://github.com/mikefarah/yq from Slack

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @baizmandesign !

I think `yq` is the better approach, unless there's some compelling reason to incorporate this into WP-CLI

**Comment by baizmandesign** [comment]
Eh, the thought was that WP CLI was already parsing the YML file—it was already in the neighborhood, so to speak. Feel free to close this issue. Thanks!
