### ISSUE TITLE
List WP contents

### ISSUE THREAD

**Issue by Horttcore** [wp-cli/ideas#18]
A command for outputting every published content from an installation would be very handy.
Ie if you want collect the average loading times of every page in your installation it would help to output every published content and let an npm script collect the loading times.
This is more of a helper function for further tooling.

**Comment by danielbachhuber** [comment]
How would this be different than running `wp post list --field=url` ?

**Comment by Horttcore** [comment]
Yeah you are right
wp post list --post_type=any --field=url will create the same effect

**Comment by danielbachhuber** [comment]
Thanks for asking!
