### ISSUE TITLE
Comment cleanup

### ISSUE THREAD

**Issue by anantshri** [wp-cli/ideas#20]
Generally with akismet enabled blogs have minimal spam in comments but those comments could not be deleted directly owing to the point that some might be incorrectly flagged hence i have generally seen people asking akismet to mark as spam not delete. 

Deleting junk spam comments via control panel GUI is a cumbersome process. Would be wonderful if we can have some more options around wp-cli comment delete command to delete any with status trash etc something like

``` 
wp comment trash cleanup
```

**Comment by ernilambar** [comment]
This will cleanup trash.
`wp comment delete $(wp comment list --status=trash --format=ids)`

**Comment by anantshri** [comment]
that i am aware of and i do use it. but looking for a cleaner approach to it.
