### ISSUE TITLE
Remove old versions of plugins, themes, core from CLI cache

### ISSUE THREAD

**Issue by billc108** [wp-cli/ideas#23]
wp-cli currently caches older version of plugins, themes, and core in a directory on the server.  It is common for some plugins to have multiple updates in a single month (sometimes the same day).  

This would be a command to delete non-current versions from the wp-cli cache.  

A possible extension would be to retain the most recent X number of previous versions.

**Comment by schlessera** [comment]
This was added as `wp cli cache prune`.
