### ISSUE TITLE
search-replace on dump file

### ISSUE THREAD

**Issue by tedmasterweb** [wp-cli/ideas#26]
This is a simple request to be able to do a search-replace on a sql dump file (.sql).

**Comment by danielbachhuber** [comment]
Have you seen the `--export=<file>` argument for `wp search-replace`? This might help you achieve the same effect.

**Comment by tedmasterweb** [comment]
If there was an `--input=<file>` to accompany it, it would be perfect. Note that I'm trying to bypass touching the database altogether.

**Comment by danielbachhuber** [comment]
> If there was an `--input=<file>` to accompany it, it would be perfect.

Ah. I think this would be a bit tricky. PHP would need to interpret all of SQL statements within the `.sql` file, perform the search-replace procedure, and then write the SQL statements back out to the file.

> Note that I'm trying to bypass touching the database altogether.

Why?

**Comment by tedmasterweb** [comment]
We have some junior developers on staff and to keep them moving forward I sometimes do things for them. If they need the URLs updated, they can just send me the file, I modify it, and send it back to them.

I totally hear your concerns though. Normally I do it using BBEdit (my text editor) but sometimes I'm on the server, and my `sed` and `awk` skills simply aren't what they should be.

**Comment by AaronHolbrook** [comment]
Would it be possible to build/create a tmp table to perform the `SQL` transactions?

**Comment by danielbachhuber** [comment]
> Would it be possible to build/create a `tmp` table to perform the SQL transactions?

This would still require a working database connection.

Thanks again for the suggestion @tedmasterweb. I'm in the process of updating WP-CLI's Philosophy document: https://github.com/wp-cli/handbook/pull/139

One core principle is that WP-CLI commands must interact with WordPress in some way. Given this principle, performing a search/replace procedure on a standalone `.sql` file is outside the scope of the project.
