### ISSUE TITLE
Check if Installed Plugins Are No Longer in the Plugin Directory

### ISSUE THREAD

**Issue by miya0001** [wp-cli/ideas#36]
https://wptavern.com/how-to-check-if-installed-plugins-are-no-longer-in-the-plugin-directory

Displays whether it is in plugin directory like following.

```
$ wp plugin list
+-----------------------+--------+--------+---------+-----------------+
| name                  | status | update | version | wordpress.org   |
+-----------------------+--------+--------+---------+-----------------+
| hello-dolly           | active | none   | 1.6     | true            |
| jetpack               | active | none   | 4.6     | true            |
| my-plugin             | active | none   | 0.1.0   | false           |
+-----------------------+--------+--------+---------+-----------------+
```

**Comment by 1naveengiri** [comment]
can you suggest in points? how it will be helpful.

**Comment by swissspidy** [comment]
I recently created this as a composer drop-in: https://github.com/wearerequired/composer-scripts

It's useful when you want to quickly list abandoned plugins that you should probably replace.

**Comment by danielbachhuber** [comment]
@swissspidy It looks like your implementation simply compares the `last_updated` value from the plugins API. If this is the case, the WP-CLI implementation could add an optional `last_updated` column to `wp plugin list` with some human-readable value.

**Comment by swissspidy** [comment]
Yep, could be as simple as that.

**Comment by eriktorsner** [comment]
Couldn't tell from reading the code, but does it detect plugins that are removed from the wordpress.org repo?

**Comment by swissspidy** [comment]
Yes, that composer drop-in detects if a plugin:

* has been pulled from the WordPress Plugin Directory (usually still available via Subversion).
* has not been updated in over two years and thus should be used carefully.

**Comment by marksabbath** [comment]
Working on this one.

**Comment by marksabbath** [comment]
I've implemented this [here](https://github.com/marksabbath/extension-command/tree/feature/check-wp-repo) and since it needs to contact the wp repository, `wp plugin list` is considerably slowed.

At this point, I'm not sure if this is something that would fit in the `wp plugin list` itself.

Could someone review the code and let me know if there's anything we could do to make it better?

**Comment by janw-me** [comment]
I will work on this today.

**Comment by marioy47** [comment]
Question: I work offline a lot. Will this make the command fail if there is no Internet access?

**Comment by swissspidy** [comment]
@marioy47 No, ideally this should just silently not show anything in this case :-) We were also discussing multiple things today like caching results and adding an option to completely skip this check (like `--skip-update-check`)

**Comment by janw-me** [comment]
It's a slow process to check to begin with.
So the way I'm implementing it, it will only show when you add the with `--fields=name,wp_org,wp_org_updated` and you can also see the wp.org update date.
