### ISSUE TITLE
wp profile for wp-admin

### ISSUE THREAD

**Issue by colemanedwards** [wp-cli/ideas#37]
It would be very useful if wp profile analyzed php execution of wp-admin views since we often see slow performance from these pages

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @colemanedwards !

This is a duplicate of https://github.com/wp-cli/profile-command/issues/18

**Comment by colemanedwards** [comment]
Ah! Great, thanks. I did look through profile-command/issues but didn't notice that one 😩. Makes sense!
