### ISSUE TITLE
a for loop based WP-CLI command to update all sites under document root at once

### ISSUE THREAD

**Issue by ghost** [wp-cli/ideas#39]
I suggest adding a new command that can be added anywhere in the system which updates all websites in a total way. As for now I do:

`for dir in /var/www/html/*/; do cd "$dir" && wp plugin update --all && wp core update ; done`

I don't have any problem but people who are very new to linux and just getting used to it might not feel comfortable working with such a long command so I offer 2 things:

* Making a WP-CLI shorter syntax command that does the same thing.
* Making sure the new "total update command" will also update themes.

**Comment by danielbachhuber** [comment]
For finding WordPress installs on the filesystem, you might want to check out https://github.com/wp-cli/find-command

Generally, I lean more towards helping users learn more about existing CLI tools, than replicating those tools in WP-CLI. See our "Shell friends" doc on this topic: https://make.wordpress.org/cli/handbook/shell-friends/

Do you have any suggestions on how we could improve our documentation, etc.?


> Making sure the new "total update command" will also update themes.

Related https://github.com/wp-cli/ideas/issues/16

**Comment by Benosika** [comment]
> Do you have any suggestions on how we could improve our documentation, etc.?

I would add a note in the "commands" section regarding to automizing update of plugins, core, when a user has 2 or more sites. That's what I personally looked for in the command section at the time.

**Comment by viktorbijlenga** [comment]
A regular bash alias would maybe be a good idea to make this easier.
https://bash.cyberciti.biz/guide/Create_and_use_aliases

**Comment by Benosika** [comment]
Of course I can create a Bash alias, but new users not necessarily can. My point is that we should make this more accessible to new users via a WP-CLI command.

**Comment by viktorbijlenga** [comment]
This could be done through great documentation I think instead.

**Comment by danielbachhuber** [comment]
Documentation is the best place for this. I've created a new issue for it: https://github.com/wp-cli/handbook/issues/175
