### ISSUE TITLE
Provide a way to run commands in Docker containers

### ISSUE THREAD

**Issue by chriszarate** [wp-cli/ideas#41]
In the manner of `--ssh`, provide a way to run wp-cli inside a running Docker container (perhaps obviously, wp-cli would need to be installed in the container). In effect, this would be a shortcut to this command:

```sh
docker exec -it -u [user] [container name or id] wp --path=[path] command
```

Aliases in `wp-config.yml` would be similarly supported.

Should this feature, if it is desired, be supported under `--ssh` or a new global parameter? Not adding a global parameter is valuable (even if "ssh" is a misrepresentation of how the command is run). One possible syntax for a connection string might be:

```
wp --ssh=user@container/my/path/ command
```

This, however, conflicts with SSH connection strings, so we'd need some sort of arbitrary prefix and delimiter, e.g.:

```
wp --ssh=docker:user@container/my/path
```

Is this a useful addition or are users better served with their own shell aliases?

**Comment by danielbachhuber** [comment]
`docker:` as an arbitrary prefix and delimiter seems like a reasonable approach to me.

**Comment by danielbachhuber** [comment]
@chriszarate Up for submitting a pull request for this?

**Comment by chriszarate** [comment]
Will do, been a little sidetracked but will put it together

**Comment by chriszarate** [comment]
Opened a PR: https://github.com/wp-cli/wp-cli/pull/4240

**Comment by danielbachhuber** [comment]
🔨
