### ISSUE TITLE
Subcommands for working with multi-dimensional values

### ISSUE THREAD

**Issue by aaemnnosttv** [wp-cli/ideas#42]
E.g.

```php
wp_update_option('example_option', array('foo' => 'bar'));
```

```
wp option pluck example_option foo
# or 
wp option get example_option --key=foo
```
Returns `bar`

```
wp option patch example_option foo baz
# or
wp option set example_option --key=foo baz
```
Updates `bar` to `baz`

Ideally it would be great to be able to use dot notation using the normal functions, but option names could contain dots or really any other character that could be used to separate hierarchy.

e.g.
```
wp option get example_option.foo
```
Returns `bar`

This same idea could be applied to just about all `get` `set` commands, for meta, transient, etc.

**Comment by danielbachhuber** [comment]
`wp option pluck` and `wp option patch` are interesting approaches.

The dot notation idea came up before (might've been you, can't find the issue), but option names can contain dots.

**Comment by schlessera** [comment]
I think the `get` and `set` variations are too error-prone. Way too easy to unintentionally overwrite your entire option array.

`pluck` and `patch` would make this more explicit, the opportunity for error is therefore reduced.

**Comment by aaemnnosttv** [comment]
Are you guys open to a PR for `pluck` and `patch`?

**Comment by schlessera** [comment]
@aaemnnosttv Yes, these might come in handy, and this specific approach is the safest one we are aware of.
