### ISSUE TITLE
Add "Changelog" section to command documentation.

### ISSUE THREAD

**Issue by gitlost** [wp-cli/ideas#43]
As mentioned in this media command issue https://github.com/wp-cli/media-command/issues/15, new options added to versions need to indicated in some way.

A simple method might be to do what PHP doc does and have a CHANGELOG section:
```
	 *
	 * ## CHANGELOG
	 *
	 * 1.2.0 Added option [--image_size=<image_size>].
	 *

```
which would be stripped on command line help.

**Comment by danielbachhuber** [comment]
> As mentioned in this media command issue wp-cli/media-command#15, new options added to versions need to indicated in some way.

@gitlost Could you explain in greater detail why this needs to be the case? The implicit assumption is that everyone is running the latest stable release, as that's the only supported version.

**Comment by schlessera** [comment]
Generally, change logs are useful to users and other developers to:

- Check changes before an update to know what could potentially break, and run extra tests for these cases.
- Have data about minimum version requirements to put on extending code.

In our case, we have very detailed release notes that should cover both of these cases. So, while I am all for change logs, putting these into all the individual packages, while still recollecting them in the release notes is probably not worth the additional effort.

**Comment by danielbachhuber** [comment]
Ok. We'll close this as 'maybelater' for now.
