### ISSUE TITLE
wp blame

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/ideas#44]
I'd like to have a command which works like `git blame` for WordPress post content in order to deduce who was responsible for introducing or last editing a given line of content. It could use the revisions API in order to calculate this.

It would be great to have an accompanying command for displaying the line number of each line in the post content as a pre-cursor to the above.

**Comment by danielbachhuber** [comment]
@johnbillion For further context, could you share the real-world use case motivating the feature?

If this is something we move forward with, it'd be neat to abstract the implementation to a standalone library, so it could be rendered by both a plugin and a command. Or, maybe this should just be a plugin.

**Comment by johnbillion** [comment]
The use case here is a client who wanted to quickly determine which user made a change to a line but didn't want to trawl through a bunch of revisions.

In reality the client found the revision via the revisions screen, but a cli command would have been helpful.

**Comment by johnbillion** [comment]
I think this is plugin material by the way.

**Comment by danielbachhuber** [comment]
> I think this is plugin material by the way.

Yes, it seems like it'd be cool to have a web interface for too.
