### ISSUE TITLE
Feature Request: wp site list -- add status

### ISSUE THREAD

**Issue by corradomatt** [wp-cli/ideas#47]
When listing sites on a multisite network it would be great if the status of the site was listed in the default `wp site list` command. By status I mean it would be either `active`, `archived`, `deleted` or `spam`.

In this way we could filter the list output by the status of the site(s). I'd like to try my hand with a PR for this and just wanted to start the conversation before I write any code. Comments, pros-cons and suggestions are welcomed.

**Comment by danielbachhuber** [comment]
Hi @corradomatt,

The status is actually represented by different attributes on the site object: `public`, `archived`, `mature`, etc. Each attribute can have 1 or 0 to designates its status. You can list sites with their attributes by using, as an example, `wp site list --fields=public,archived,spam`

As such, it would be lossy to try to consolidate these into a single `status` attribute.

Could you describe your use case in better detail so we can better understand what you're trying to do?

**Comment by corradomatt** [comment]
oh! duh...thanks @danielbachhuber - I didn't realize that these were fields setup this way. I can do everything I need with `--public=1 --archived=0 --deleted=0 --spam=0`
