### ISSUE TITLE
Add new command: generate-alt-tags (maybe for plugin "media-command")

### ISSUE THREAD

**Issue by Cyb0rk** [wp-cli/ideas#49]
Hi there,

because WP doesn't automatically create `alt` tags for `<img` anymore I need a command to autofill the alt tags for all my images.

I already wrote a command for this and use it on my sites. Maybe you like it and it could be implemented in wp-cli.

See the code at: https://gist.github.com/Cyb0rk/71d9658887755a0dea3cf543d67c0310

**Comment by danielbachhuber** [comment]
Thanks for the suggestion @Cyb0rk.

> because WP doesn't automatically create `alt` tags for `<img` anymore I need a command to autofill the alt tags for all my images.

This is interesting. Do you know why this decision was made?

**Comment by Cyb0rk** [comment]
@danielbachhuber No, I don't know it. Sorry.

**Comment by GaryJones** [comment]
https://make.wordpress.org/core/2016/11/11/improving-accessibility-of-image-alternative-text-in-4-7/

The key points are:

- alt attributes (not tags) cannot be reliably auto-generated with doing image analysis, and even then it's a best guess.
- alt attributes can (and should) be left empty under certain circumstances (like the image being purely decorative, or having a suitably descriptive caption associated with the image).

As such, I'd be strongly against the introduction of any such "generation-alt-tags" command, for the bad practices (and poor quality output) it will facilitate.

**Comment by danielbachhuber** [comment]
> for the bad practices (and poor quality output) it will facilitate.

This seems like a reasonable conclusion. Thanks @GaryJones
