### ISSUE TITLE
Alfred workflow for looking up WP-CLI commands

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/ideas#58]
It'd be neat to have an [Alfred App](https://www.alfredapp.com/) workflow for looking up WP-CLI command information.

We could expose command docs in the developer.wordpress.org REST API. 💯 if we could actually display the documentation within Alfred.

Related https://github.com/keesiemeijer/alfred-wordpress-developer-workflow

**Comment by GaryJones** [comment]
One solution would be to use [Dash](https://kapeli.com/dash), which hooks into Alfred nicely.

![screenshot of Alfred and Dash](https://user-images.githubusercontent.com/88371/31417262-31a06344-ae26-11e7-83ef-e4ae44094660.png)


Dash has many (150+) existing offline docsets, including WordPress:

![screenshot of Dash](https://user-images.githubusercontent.com/88371/31417119-7f2ab94e-ae25-11e7-855f-bffbc61da2f1.png)

These Docsets can be [created](https://kapeli.com/docsets) from parsed DocBlocks within the code, so a good reason to have WP-CLI adhere to `WordPress-Docs` coding standards, rather than creating separate long-form content for each and every command.

**Comment by GaryJones** [comment]
https://twitter.com/magicroundabout/status/918373008854650880

**Comment by rosswintle** [comment]
So, I use Dash. And a while ago I checked in with @schlessera about what the copyright status of the docs is and he said they were GPL and so I could use them. I'm really keen not to do something that's wrong or that breaks the rules. But I have, just today, made a Dash DocSet of the command reference: https://github.com/rosswintle/wpcli-dashdocs

It's not quite ready for prime time, and the generator code that creates the docs is a bit hacked together (to my shame).  But it's a first stab and if you grab the repo and open the .docset in Dash it works!

**Comment by rosswintle** [comment]
Worth nothing that I created these by scraping the online docs with wget, and then processing the files and generating the index. I've maintained a GPL license.  I hadn't considered that you could grab stuff from the docblocks and comments in the WP-CLI code.

**Comment by GaryJones** [comment]
![screen shot 2017-10-12 at 23 12 57](https://user-images.githubusercontent.com/88371/31521826-e4c33050-afa2-11e7-9b55-7a1dea520ff8.png)

Adding the keyword to my Alfred workflow seemed to work fine.

**Comment by rosswintle** [comment]
This Alfred keyword should be added automatically by Dash. I'll contact the Dash guy and see if this maybe doesn't work for locally-added docsets.

**Comment by patrik-csak** [comment]
I've [contributed](https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/WP-CLI) WP-CLI documentation to Dash's User Contributed Docsets, so you can install it straight from Dash. The docsets are [generated](https://github.com/ptrkcsk/wp-cli-dash-docset-generator) from the source Markdown files in the [handbook repo](https://github.com/wp-cli/handbook/tree/master/commands) (scraping worked okay at first, but for a while the command index was completely broken) and support all available [releases](https://github.com/wp-cli/handbook/releases).

**Comment by rosswintle** [comment]
Great work - I'd done 80% of the work, but you've finished it off. Thank you!

**Comment by GaryJones** [comment]
Thanks @ptrkcsk!

**Comment by danielbachhuber** [comment]
Amazing @ptrkcsk ! Let us know if you need any help along the way. Happy to move the repo to the WP-CLI organization if you'd prefer.

**Comment by patrik-csak** [comment]
@danielbachhuber I'm open to it! Could you let me know how that would work?

**Comment by danielbachhuber** [comment]
You'd simply need to add me as a collaborator on the repo. I'd complete the transfer process, and then add you back as a collaborator.

From that point, you can take responsibility for generating the docs as long as you'd like. The project would benefit from visibility and contribution by being a part of the WP-CLI organization.

**Comment by patrik-csak** [comment]
Done!

**Comment by danielbachhuber** [comment]
Oops, that wasn't quite it:

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/36432/36903040-47792446-1de1-11e8-8000-e86b8e7bcb80.png">

Can you use the "Transfer Ownership" feature in the Settings screen to transfer ownership to me? Once you've done so, I'll transfer to the WP-CLI organization.

**Comment by patrik-csak** [comment]
Done!

**Comment by danielbachhuber** [comment]
Cool, we're live: https://github.com/wp-cli/dash-docset-generator

I've filed an issue to add documentation: https://github.com/wp-cli/handbook/issues/213

Thanks again!
