### ISSUE TITLE
Feature Request: WP core download with no content

### ISSUE THREAD

**Issue by AaronRutley** [wp-cli/ideas#59]
Hi 👋 

Aaron here, I'm a big fan of WP-CLI ! 

I'd really like to be able to install WordPress without any default themes or plugins.

I can see the 'no content' zip is available at this endpoint:
https://api.wordpress.org/core/version-check/1.7/

Something like `wp core download --no_content` would be awesome!

**Comment by schlessera** [comment]
Yes, agree this would be worthwhile.

It should be a flag `--content` that defaults to `true`. This way, `--no-content` will disable it. Also, you'll be able to use `content: true` or `content: false` in config files.

**Comment by AaronRutley** [comment]
Great! I'm keen to help on a PR. 

I've just been doing some testing on a bash script[ that I have to automate installs](https://github.com/aaronrutley/valetpress). 
I'm able to get my wp install down from 4.7 seconds to 1.3 seconds if I use the no-content zip!

**Comment by danielbachhuber** [comment]
`--skip-content` would be the more appropriate flag.

@AaronRutley I'm now amenable to the idea if you'd like to invest time into it.

Previously: https://github.com/wp-cli/wp-cli/issues/1978#issuecomment-245776874

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/wp-cli/core-command/issues/36
