### ISSUE TITLE
Support bootstrap file for `wp shell`

### ISSUE THREAD

**Issue by schlessera** [wp-cli/ideas#65]
It would be useful to support providing the location of a bootstrap file to `wp shell` from within a `wp-cli.yml` configuration file.

This bootstrap file would only be included when running an interactive `wp shell` session, and thus allow for setting up any tedious preparation that is necessary for debugging/testing.

**Comment by danielbachhuber** [comment]
This can already be done with something like:

```
$ cat
<?php shell-bootstrap.php
WP_CLI::add_hook( 'before_invoke:shell', function() {
    // do something
});
$ wp --require=shell-bootstrap.php shell
````

I don't know if we need to solve the problem further than this. Adding it to the docs would be good though.
