### ISSUE TITLE
Permit defining abspath before WP-CLI is loaded

### ISSUE THREAD

**Issue by janw-me** [wp-cli/ideas#69]
If ABSPATH is defined before wp-cli loads it will throw a notice.

**Example.**
`wp-cli.yaml`

    require:
         - abspath.php

`abspath.php`

    <?php
    if ( ! defined( 'ABSPATH' ) ) {
	    define( 'ABSPATH', dirname( __FILE__ ) . '/pubic_html/wp/' );
    }

Now if you run any wp-cli it will throw a notice that ABSPATH is already defined. 

**When would you want this?**
In short symlinks, if you include WordPress in a symlink.

WordPress tries to define the ABSPATH it uses `wp-load.php` and if it's in a symlink it will define the path baed on the actual location. Not the symlink path.
That will give a problem if the `wp-config.php` is one directory above `wp-load.php`

The file structure of this with my example to help visualize this.

 - `./public_html/index.php`  < the webroot
 - `./public_html/wp-config.php`
 - `./public_html/wp` < symlink to `/opt/wordpress/`
 - `./public_html/wp/wp-load.php` < here the ABSPATH is based on

`ABSPATH` will be `/opt/wordpress/`, but you would want it to be `./public_html/wp/` so wp-load will look for `./public_html/wp-config.php`

**The fix.**
Just add a check if ABSPATH is already defined. I have the fix ready in my [fork](https://github.com/janw-oostendorp/wp-cli/commit/99b458898eab4ae7c58ac24c2d056af996ea97e1)

**Comment by danielbachhuber** [comment]
Previously:

> While it seems easy enough to make this change, WP-CLI has historically only officially supported WordPress install configurations that you can also achieve through the web interface. Introducing this check implies we support every potential installation configuration, which is a rabbit hole I'm not keen to enter.

From https://github.com/wp-cli/wp-cli/issues/4054#issuecomment-300153660

**Comment by janw-me** [comment]
This kind of setup _can_ be achieved through the web interface. If you check [wp-load.php:20](https://github.com/WordPress/WordPress/blob/master/wp-load.php#L20) This check is the first thing in the file.

So when for example I go to the [wp-login](https://github.com/WordPress/WordPress/blob/master/wp-login.php) the first thing it does is include wp-load.php. Which tries to define the `ABSPATH`.

But where is this alternative `ABSPATH` defined for the web interface you ask.
I let the webserver do an [auto-prepend-file](https://secure.php.net/manual/en/ini.core.php#ini.auto-prepend-file) of the `abspath.php`

I have this setup running for a week in test mode and in the web interface I haven't encountered problems.
I wouldn't say I've tested every little thing. But the things I have tested include. uploads, rest api, wp-admin, login, crud of posts/pages/taxonomies, installing plugin's, theme's.

Are there specific things that come to mind that worry you with this setup?
Or might there be extra checks that might help to prevent problems/warn users.

Maybe add an extra debug message when `ABSPATH` is defined in this kind of way.

**Comment by danielbachhuber** [comment]
> So when for example I go to the wp-login the first thing it does is include wp-load.php. Which tries to define the `ABSPATH`.

Oh, huh:

![image](https://user-images.githubusercontent.com/36432/33349266-3c19d8e8-d44e-11e7-81bf-413a064a4e5f.png)

Maybe WordPress does support `ABSPATH` defined before PHP execution: https://github.com/WordPress/WordPress/commit/4074bcc6a11170b8183bef40fede0c7c133e155d

https://core.trac.wordpress.org/ticket/26592

> Are there specific things that come to mind that worry you with this setup?

More so: unintended consequences. If we permit this and it causes problems X, Y and Z down then line, then I'd rather not let this happen in the first place.

But, given WordPress supports it, I'm open to it. Want to submit a pull request with [functional tests](https://make.wordpress.org/cli/handbook/pull-requests/#running-and-writing-tests)?

**Comment by janw-me** [comment]
Functional tests. Yes, this is new to me. I'll look into it. I'll expect between the holidays at last.

**Comment by schlessera** [comment]
Just let us know if you happen to get stuck with the tests.

**Comment by danielbachhuber** [comment]
Looking into this briefly, we'll also need to accommodate `--path=<path>`. Because `--path=<path>` is a way of defining the path to WordPress at runtime, we'll have somewhat ambiguous behavior if we also support definition of `ABSPATH` at runtime.

**Comment by schlessera** [comment]
Implemented via https://github.com/wp-cli/wp-cli/pull/4743
