### ISSUE TITLE
New command wp media fixorientation

### ISSUE THREAD

**Issue by tealborder** [wp-cli/ideas#70]
> Opening an issue before submitting a pull request helps us provide architectural and implementation guidance before you spend too much time on the code.

Ideal new cli command: `wp media fixorientation`

Been thinking about implementing this today as a plugin, but figured it would be more fun to put this in the hands of devs at the cli for bulk rotating images because exif orientation tags.

Currently, there hardly exists any plugins in the wp plugin repo for auto-orientation on existing wp media images. Plenty of plugins though for auto-orientation during upload.

**Comment by danielbachhuber** [comment]
Interesting idea! It'd be great to have a `--dry-run` flag too, so you could see which image files would be impacted before running it.
