### ISSUE TITLE
Generate README.md from readme.txt for plugins

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/ideas#74]
[grunt-wp-readme-to-markdown](https://www.npmjs.com/package/grunt-wp-readme-to-markdown) is a Grunt plugin to generate `README.md` from `readme.txt`.

It would be helpful for plugin authors to have a WP-CLI command for this same task, so Grunt becomes unnecessary.

Related #68 https://github.com/WordPress/packages/pull/55#issuecomment-353349613

**Comment by swissspidy** [comment]
I used to use this Grunt plugin, but decided that it makes more sense to have separate `README.md` and `readme.txt` files in my plugins.

Why? The readme on GitHub is aimed at developers and contains things like build status, contribution guidelines, etc. The readme.txt on WordPress.org on the other hand is for end users and contains things like screenshots, FAQs, marketing bla-bla, etc.
