### ISSUE TITLE
Show loader during wp db import

### ISSUE THREAD

**Issue by BhargavBhandari90** [wp-cli/ideas#79]
Can we show loader during `wp db import`.

Currently, it's not showing anything. It would be better if we show loader. So that user can understand that process is still going on.

Don't know if this is achievable or not.

**Comment by schlessera** [comment]
`wp db import` is basically just a wrapper around the `mysql` binary.

Given that we support multiple platforms and multiple DB drivers (`mysql` could for example be MariaDB instead), it would be very difficult to produce something reliable across all environments.

You should be able to use [PipeViewer](https://www.ivarch.com/programs/pv.shtml) to achieve this yourself:
```
pv dbdump.sql | wp db import -
```
