### ISSUE TITLE
Community Promotion Ad on StackOverflow

### ISSUE THREAD

**Issue by schlessera** [wp-cli/ideas#83]
@hofmannsven would like to create a [Community Promotion Ad on StackOverflow](https://wordpress.meta.stackexchange.com/q/4464/32946) for WP-CLI.

I'll create individual comments below here with each of the propositions we have so far, and we would love to get feedback on them.

So, vote on the comments, or add your own feedback comments. Let us know what you think and share your ideas!

**Comment by schlessera** [comment]
![wp-cli-ad-2018_v1](https://user-images.githubusercontent.com/83631/36042258-8922193c-0dcb-11e8-8519-f5d1643ca7a0.png)

**Comment by schlessera** [comment]
![wp-cli-ad-2018_v2](https://user-images.githubusercontent.com/83631/36042277-9514313a-0dcb-11e8-9946-60d1e4b09a2e.png)

**Comment by schlessera** [comment]
![wp-cli-ad-2018_v3](https://user-images.githubusercontent.com/83631/36042285-9ec13084-0dcb-11e8-966b-80fd04c3e994.png)

**Comment by joyously** [comment]
I like the color one, and it would catch more eyes than black and white. But it seems a bit vague and pointless. Maybe a more action oriented phrase, such as "Control multiple WordPress sites from one command line"  ?

**Comment by Themesfinity** [comment]
Here I would like to go with the first one as it looks good compared to other two. I agree with what "joyously" suggested about the phrase and it makes sense.

**Comment by frankiejarrett** [comment]
Is the objective for the ad to create brand awareness to a demographic that doesn’t know what “CLI” means?

I think a tag line that describes the value proposition is a more intriguing/powerful way to introduce something:

“The fastest way to WordPress.”

Where WordPress could be read as a proper noun or verb and it still makes sense.

Just food for thought! Love the colorful number 3 design! In order my favs are: 3, 2, 1

**Comment by logicalphase** [comment]
The first black and white ad is in keeping with the original branding, and contrast is good. I like that. Don't like the washed color at all. 

Maybe "Take Command of WordPress"

**Comment by schlessera** [comment]
The ad that got the most votes in here was published just now:
https://wordpress.meta.stackexchange.com/a/4477/32946

Would be lovely if everyone could take a few seconds to vote on the ad at the above link, as we need to reach a minimum threshold of votes for it to become active.

Thanks for your work, @hofmannsven, and for everyone who provided feedback!
