### ISSUE TITLE
Commands to check table indexing and Convert MyISAM /InnoDB

### ISSUE THREAD

**Issue by renatonascalves** [wp-cli/ideas#85]
There are a few commands that came necessary recently to me and I'd like to suggest to wp-cli core. They are:

`wp db convert-table` Convert tables from MyISAM into InnoDB.
`wp db check-index` Check if certain tables have the index available.
`wp db create-index` Create an index for certain tables.

I started to add some base support here: https://github.com/renatonascalves/wp-cli-opt

**Comment by schlessera** [comment]
Sounds like something useful to add to the `db` command. However, I'd like to have more feedback on how reliably this work before including it by default.

Is this already being used on production sites?

**Comment by renatonascalves** [comment]
Not yet! I did some tests on local development only. I'll be trying on a production database this weekend.

**Comment by kirtangajjar** [comment]
@renatonascalves So how did it go!

**Comment by lkraav** [comment]
After experiencing a massive performance issue related to a rogue plugin putting `autoload = yes` stuff into `wp_options` (400 MB worth!), and arriving at https://core.trac.wordpress.org/ticket/24044 I would like these WP-CLI commands very much, thank you :) Since I'm now about to convert everything to InnoDB, for one.

**Comment by renatonascalves** [comment]
Update: I'll be coming back to finish this command this weekend. Thanks for the patience.

**Comment by lkraav** [comment]
> Update: I'll be coming back to finish this command this weekend. Thanks for the patience.

Great. Also, I've learned from https://serverfault.com/questions/51982/converting-big-table-from-myisam-to-innodb that converting larger tables may take a long time - commands should probably do well to warn the user about what's about to happen.
