### ISSUE TITLE
Accept a parameter to use a Different Database.

### ISSUE THREAD

**Issue by luigitec** [wp-cli/ideas#87]
I have the following situation:

We create daily MySQL and XML backups hitting a **Slave RDS** (Read only DB), to avoid suffocating our  **Production RDS**. This occurs on a Devel "cloned" instance, so, the wp-config.php file on each installation includes the following:

```
if ( defined( 'WP_CLI' ) && WP_CLI ) {
    define( 'DB_HOST', 'Prod.Slave.RDS' );
} else {
    define( 'DB_HOST', 'Devel.RDS' );
}
```

As I mentioned, it runs on a cloned instance of the Production one, but with its own Development RDS; since we want to backup the data from the live server, then we hit the Slave RDS to retrieve data from the Production installation.

**Problem**
Everything worked fine for that case, but we also use the same server to upgrade/test our WP installations, knowing that the **SLAVE RDS** is on Read-only mode, I can't run commands like `wp core update && wp core update-db && wp plugin update --all` since it wont be able to register the updates.

So, for certain commands, I want to use the **Slave RDS**, and for other commands, I want to use a different RDS. 

Is there a way to know which command is running?, e.g.

`if ( defined( 'WP_CLI' ) && WP_CLI`   && `WP_CLI['is_core']` or something like that? Or perhaps a setting on the configuration file.

I hope to make sense with this vague explanation.

**Comment by schlessera** [comment]
WP-CLI is fundamentally built to work with one installation, using that installation's `wp-config.php` file. I don't think your use case warrants deviating from that path.

What you want to do can be easily done with environment variables. You can put something like the following in your `wp-config.php` file:
```
define( 'DB_HOST', getenv( 'DB_HOST' ) || 'Devel.RDS' );
```
Then, you can run WP_CLI commands by prepending environment variables:
```
DB_HOST=Prod.Slave.RDS wp db repair
```

Hope this helps your use case!

**Comment by luigitec** [comment]
Awesome, this did the trick and now I'm using it on several other tasks. Thank you @schlessera !
