### ISSUE TITLE
Add command to manage aliases

### ISSUE THREAD

**Issue by schlessera** [wp-cli/ideas#88]
Currently, there's a single command to deal with aliases: `wp cli alias` - it outputs the known aliases.

It would be great to have more CRUD-like methods to manage aliases. The usual suspects, like `get`, `create`, `delete`, ...

**Use case 1:**
If you can't remember, on what domain/IP the current `@shop-live` is, you can just do:
```
$ wp alias get @shop-live
ssh: webdev@mybestestshop.com:12345/home/webdev/
```

**Use case 2:**
This would enable scripts that create sites to automatically add the corresponding aliases as well.

**Comment by thrijith** [comment]
Hey, @schlessera I have started on this, but wanted to make sure if this is the correct approach. Let me know your suggestions on this.

You can check the initial changes done for this over here https://github.com/thrijith/wp-cli/pull/1

Please let me know if I should open up this PR on `wp-cli/wp-cli` for its discussion.

**Comment by swissspidy** [comment]
@thrijith Sounds like a good plan to me. I already left a couple of comments.

We can then help you with adding tests.

**Comment by thrijith** [comment]
Thanks, @swissspidy, I will check the comments.
