### ISSUE TITLE
db tables auto prefix

### ISSUE THREAD

**Issue by coreyworrell** [wp-cli/ideas#98]
When using wp-cli in an automated way, we do not have an easy way to get the current database prefix, and usually we don't need it because wp-cli can grab it when it does its queries. But when using the `wp db tables <table>` or `wp db export --exclude-tables=<tables>` commands, you have to inlude the prefix (either explicitly or as a wildcard).

The wildcard leads to unwanted behavior though, such as `wp db tables *_links` can return `wp_links,wp_yoast_seo_links`. But I really only wanted the first `wp_links` table to be returned.

**Comment by schlessera** [comment]
@coreyworrell There is a `wp db prefix` command that lets you retrieve the prefix.

So, for example, you can do something like the following:
```
wp db export --exclude_tables=$(wp db prefix)links
```

I think that auto-prefixing is not explicit enough and might often produce unexpected results.
